artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/Shivan118/Main-Branching/raw/main/marketing_campaign.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data
  
